export const globalUsers = [
    {
        id: 1,
        firstName: "Travus",
        lastName: "MacGragh",
        userName: "tmacgragh0@freewebs.com",
        email: "tmacgragh0",
        password: "fB7}n7L8h",
    },
    {
        id: 2,
        firstName: "Celene",
        lastName: "Latchmore",
        userName: "clatchmore1@ocn.ne.jp",
        email: "clatchmore1",
        password: "xA4%_HF1kCW956",
    },
    {
        id: 3,
        firstName: "Jerry",
        lastName: "Caunt",
        userName: "jcaunt2@google.fr",
        email: "jcaunt2",
        password: "wH9@u}qe|~LoK6XI",
    },
    {
        id: 4,
        firstName: "Arvin",
        lastName: "Kite",
        userName: "akite3@mac.com",
        email: "akite3",
        password: "jM9=$Pan?wlq4{Jv",
    },
    {
        id: 5,
        firstName: "Matilde",
        lastName: "Ruoss",
        userName: "mruoss4@howstuffworks.com",
        email: "mruoss4",
        password: "yG4_mJ'65c6|h4F",
    },
    {
        id: 6,
        firstName: "Haven",
        lastName: "Slimon",
        userName: "hslimon5@ucoz.com",
        email: "hslimon5",
        password: "jD9(5*pdPlE",
    },
    {
        id: 7,
        firstName: "Garreth",
        lastName: "Le Friec",
        userName: "glefriec6@goo.ne.jp",
        email: "glefriec6",
        password: "wO3'HL=9>}@#Be+",
    },
    {
        id: 8,
        firstName: "Beryle",
        lastName: "Pittel",
        userName: "bpittel7@istockphoto.com",
        email: "bpittel7",
        password: "hL3/_AI&k@5#",
    },
    {
        id: 9,
        firstName: "Chastity",
        lastName: "Klaus",
        userName: "cklaus8@smh.com.au",
        email: "cklaus8",
        password: "bX0+@C6U3H",
    },
    {
        id: 10,
        firstName: "Sherlock",
        lastName: "Coulling",
        userName: "scoulling9@constantcontact.com",
        email: "scoulling9",
        password: "cL9_)|l0(d,",
    },
    {
        id: 11,
        firstName: "Valeria",
        lastName: "O'Carran",
        userName: "vocarrana@cocolog-nifty.com",
        email: "vocarrana",
        password: "jL5)XQB<",
    },
    {
        id: 12,
        firstName: "Mahmoud",
        lastName: "Zoppo",
        userName: "mzoppob@unicef.org",
        email: "mzoppob",
        password: "hQ7`9@,O(gI{7G5c",
    },
    {
        id: 13,
        firstName: "Trent",
        lastName: "Beardall",
        userName: "tbeardallc@biblegateway.com",
        email: "tbeardallc",
        password: "wM0`X.?<!dW",
    },
    {
        id: 14,
        firstName: "Val",
        lastName: "Oen",
        userName: "voend@behance.net",
        email: "voend",
        password: "jP3>p6#9y6H99",
    },
    {
        id: 15,
        firstName: "Blakeley",
        lastName: "Kernoghan",
        userName: "bkernoghane@vimeo.com",
        email: "bkernoghane",
        password: "zL6{VwLCU2ZV",
    },
    {
        id: 16,
        firstName: "Abie",
        lastName: "McGlaughn",
        userName: "amcglaughnf@cam.ac.uk",
        email: "amcglaughnf",
        password: "hC7|jOQ~+5l*Nyk<",
    },
    {
        id: 17,
        firstName: "Wright",
        lastName: "D'Alesio",
        userName: "wdalesiog@nytimes.com",
        email: "wdalesiog",
        password: "pU3(,oO@'rT",
    },
    {
        id: 18,
        firstName: "Fons",
        lastName: "Phebee",
        userName: "fphebeeh@360.cn",
        email: "fphebeeh",
        password: "qZ0%I_oLy3Y",
    },
    {
        id: 19,
        firstName: "Bary",
        lastName: "McGeorge",
        userName: "bmcgeorgei@state.gov",
        email: "bmcgeorgei",
        password: "xU4/Qne|O#S",
    },
    {
        id: 20,
        firstName: "Allis",
        lastName: "Alger",
        userName: "aalgerj@umn.edu",
        email: "aalgerj",
        password: "uC4<V5KGL+6Xdw",
    }
];